# Generated by Django 5.2.8 on 2025-11-20 12:08

from django.db import migrations


def migrate_car_data_to_car_details(apps, schema_editor):
    """Migrate existing Car data to CarDetails"""
    Car = apps.get_model('backend', 'Car')
    CarDetails = apps.get_model('backend', 'CarDetails')

    for car in Car.objects.all():
        # Create CarDetails from existing Car fields
        car_details = CarDetails.objects.create(
            brand=car.brand or '',
            model=car.model_name or '',
            year=car.year or 0,
            color=car.color
        )
        # Link the car to the new car_details
        car.car_details = car_details
        car.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration by copying data back"""
    Car = apps.get_model('backend', 'Car')

    for car in Car.objects.all():
        if car.car_details:
            car.brand = car.car_details.brand
            car.model_name = car.car_details.model
            car.year = car.car_details.year
            car.color = car.car_details.color
            car.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cardetails_remove_car_model_car_model_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_car_data_to_car_details, reverse_migration),
    ]
